/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence.system;

/**
 *
 * @author 94768
 */
public class Helicopter extends javax.swing.JFrame implements DefenceObserver {
   private MainController mainController;
   

    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        setVisible(true);
        setTitle("Helicopter"); 
    }
    
    public void setMainController( MainController mainController){
        this.mainController=mainController;
    }
    
    public MainController getMainColler(){
            return mainController;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplayHelicopter = new javax.swing.JTextPane();
        txtFieldHelicopter = new javax.swing.JTextField();
        btnSendHelicopter = new javax.swing.JButton();
        lblAreaNotClearedHelicopter = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        Sliderfuel = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        spinner = new javax.swing.JSpinner();
        lblCount = new javax.swing.JLabel();
        btnSetBullets = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        spinnerCount = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        lblSoldierCount = new javax.swing.JLabel();
        btnSetSoldiers = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtDisplayHelicopter);

        txtFieldHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHelicopterActionPerformed(evt);
            }
        });

        btnSendHelicopter.setText("Send");
        btnSendHelicopter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendHelicopterActionPerformed(evt);
            }
        });

        lblAreaNotClearedHelicopter.setText("Area Not Clearerd");

        jCheckBox1.setText("Position");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });

        Sliderfuel.setMajorTickSpacing(10);
        Sliderfuel.setMinorTickSpacing(10);
        Sliderfuel.setOrientation(javax.swing.JSlider.VERTICAL);
        Sliderfuel.setPaintLabels(true);
        Sliderfuel.setPaintTicks(true);
        Sliderfuel.setSnapToTicks(true);
        Sliderfuel.setValue(100);
        Sliderfuel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderfuelStateChanged(evt);
            }
        });

        jLabel1.setText("Fuel");

        btn1.setText("Shoot");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("Missile operataion");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("Laser Operation");

        spinner.setModel(new javax.swing.SpinnerNumberModel(1000, 0, 1000, 1));
        spinner.setValue(1000);
        spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerStateChanged(evt);
            }
        });

        btnSetBullets.setText("Set Bullets");
        btnSetBullets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBulletsActionPerformed(evt);
            }
        });

        jLabel2.setText(" Ammo Count :");

        jLabel3.setText("Soldier Count :");

        btnSetSoldiers.setText("Set Soldiers");
        btnSetSoldiers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetSoldiersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btn1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFieldHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnSendHelicopter))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(4, 4, 4)
                                        .addComponent(lblSoldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(lblCount, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinnerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSetBullets, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSetSoldiers))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(Sliderfuel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(lblAreaNotClearedHelicopter)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaNotClearedHelicopter)
                    .addComponent(btn2)
                    .addComponent(btn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sliderfuel, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btn3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCount)
                            .addComponent(jLabel2)
                            .addComponent(btnSetBullets))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(lblSoldierCount)
                            .addComponent(btnSetSoldiers))
                        .addGap(76, 76, 76)
                        .addComponent(jCheckBox1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldHelicopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendHelicopter))
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHelicopterActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHelicopterActionPerformed

   boolean position=true;
   
    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        position = evt.getStateChange()==java.awt.event.ItemEvent.SELECTED;
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void btnSendHelicopterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendHelicopterActionPerformed
        String textMessage=txtFieldHelicopter.getText();
         mainController .receivedMessage("Helicopter : "+textMessage);
        
    }//GEN-LAST:event_btnSendHelicopterActionPerformed

    private void SliderfuelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderfuelStateChanged
     /*  for(int i=100;i>=0;i--){
        try{
            Thread.sleep(1);
        } catch(InterruptedException ex){
            Sliderfuel.setValue(i);
        
        }
       }*/
    }//GEN-LAST:event_SliderfuelStateChanged

    
    //to set Bullets count
 
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
        if(position==true){
         int val=Integer.parseInt(lblCount.getText());
         int newVal=val-1;
         lblCount.setText(Integer.toString(newVal));
        }else{
              btnSetBullets.disable();
        
        }    
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void spinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerStateChanged
                // TODO add your handling code here:
    }//GEN-LAST:event_spinnerStateChanged

    private void btnSetBulletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBulletsActionPerformed
         lblCount.setText(spinner.getValue().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetBulletsActionPerformed

    
    //to set Soilder count
    private void btnSetSoldiersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetSoldiersActionPerformed
    
        if(position==true){
              lblSoldierCount.setText(spinnerCount.getValue().toString());
        }  else{
       btnSetSoldiers.disable();
        
        }
    }//GEN-LAST:event_btnSetSoldiersActionPerformed


 
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Sliderfuel;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btnSendHelicopter;
    private javax.swing.JButton btnSetBullets;
    private javax.swing.JButton btnSetSoldiers;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblAreaNotClearedHelicopter;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblSoldierCount;
    private javax.swing.JSpinner spinner;
    private javax.swing.JSpinner spinnerCount;
    private javax.swing.JTextPane txtDisplayHelicopter;
    private javax.swing.JTextField txtFieldHelicopter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(int sliderLevel) {
      if(position==true){
       if(sliderLevel>=20){
            btn1.setText("Shoot on");
           btn1.enable();
       }
       else if(sliderLevel<20){
         btn1.setText("Shoot ");
            btn1.disable();
       }
       if(sliderLevel>=40){
           btn2.setText("Missile operation on");
           btn2.enable();
       }
       else if(sliderLevel<40){
           btn2.setText("Missile Operation ");
           btn2.disable();
       }
       if(sliderLevel>=60){
           btn3.setText("Laser Operation On ");
           btn3.enable();
       }
       else if(sliderLevel<60){
           btn3.setText("Laser Operation ");
           btn3.disable();
       }
}
      else{
          btn1.setText("Shoot");
          btn1.disable();
          
          btn2.setText("Missile Operation");
          btn2.disable();
          
          btn3.setText("Laser Operation");
          btn3.disable();

        }
   }    
    
    @Override
     public void setAreaClearedText(String text){
             lblAreaNotClearedHelicopter.setText(text);
 }

    @Override
    public void updateText(String text) {
           txtDisplayHelicopter.setText("Main controller :"+text);
        
    }
}
