/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence.system;

/**
 *
 * @author 94768
 */
public  class Submarine extends javax.swing.JFrame  implements DefenceObserver {
           private MainController mainController;
    /**
     * Creates new form Submarine
     * @param maincontroller
     */
    public Submarine( ) {
        initComponents();
         setVisible(true);
         setTitle("Submerine");
      
    }
    
        public void setMainController( MainController mainController){
        this.mainController=mainController;
    }
    
    public MainController getMainColler(){
            return mainController;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSubmarineDisplay = new javax.swing.JTextPane();
        txtFieldSubmarine = new javax.swing.JTextField();
        btnSendSubmarine = new javax.swing.JButton();
        lblAreaNotClearedSubmarine = new javax.swing.JButton();
        checkBoxSubmarine = new javax.swing.JCheckBox();
        btnS1 = new javax.swing.JButton();
        btnS3 = new javax.swing.JButton();
        btnS2 = new javax.swing.JButton();
        btnS4 = new javax.swing.JButton();
        btnSoldier = new javax.swing.JButton();
        btnAmmo = new javax.swing.JButton();
        spinnerSolder = new javax.swing.JSpinner();
        spinnerAmmo = new javax.swing.JSpinner();
        lblSoldier = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAmmo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtSubmarineDisplay);

        txtFieldSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSubmarineActionPerformed(evt);
            }
        });

        btnSendSubmarine.setText("Send");
        btnSendSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSubmarineActionPerformed(evt);
            }
        });

        lblAreaNotClearedSubmarine.setText("Area Not Cleared");

        checkBoxSubmarine.setText("Position");
        checkBoxSubmarine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxSubmarineItemStateChanged(evt);
            }
        });

        btnS1.setText("Shoot");
        btnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS1ActionPerformed(evt);
            }
        });

        btnS3.setText("Sonar Operation");

        btnS2.setText("Tomahawk Missile");

        btnS4.setText("Trident-2 Missile");

        btnSoldier.setText("Set Soldier");
        btnSoldier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoldierActionPerformed(evt);
            }
        });

        btnAmmo.setText("Set Ammo");
        btnAmmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmmoActionPerformed(evt);
            }
        });

        spinnerAmmo.setModel(new javax.swing.SpinnerNumberModel(1000, 0, 1000, 1));

        lblSoldier.setText("jLabel1");

        jLabel2.setText("Soldier Count :");

        lblAmmo.setText("jLabel3");

        jLabel4.setText("Ammo Count :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnS2)
                            .addComponent(checkBoxSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAreaNotClearedSubmarine)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnS4)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnS1)
                        .addGap(73, 73, 73)
                        .addComponent(btnS3)
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoldier, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerSolder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSoldier))))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFieldSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSendSubmarine)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnS1)
                    .addComponent(btnS3)
                    .addComponent(btnSoldier)
                    .addComponent(spinnerSolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoldier)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnS2)
                            .addComponent(btnS4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblAmmo)
                            .addComponent(spinnerAmmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAmmo))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaNotClearedSubmarine)
                    .addComponent(checkBoxSubmarine))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendSubmarine))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSubmarineActionPerformed
          String textMessage=txtFieldSubmarine.getText();
         mainController.receivedMessage("Submarine : "+textMessage);
    }//GEN-LAST:event_btnSendSubmarineActionPerformed

    private void txtFieldSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSubmarineActionPerformed

    private void checkBoxSubmarineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxSubmarineItemStateChanged
        position = evt.getStateChange()==java.awt.event.ItemEvent.SELECTED; 
    }//GEN-LAST:event_checkBoxSubmarineItemStateChanged

    //Set Soldier Count to lable
    private void btnSoldierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoldierActionPerformed
  
        if(position==true){
              lblSoldier.setText(spinnerSolder.getValue().toString());
        }  else{
      btnSoldier.disable();
        
        }
    }//GEN-LAST:event_btnSoldierActionPerformed

    //set Ammo Count to Label
    private void btnAmmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmmoActionPerformed
        if(position==true){
               lblAmmo.setText(spinnerAmmo.getValue().toString());   
        }  else{
            btnAmmo.disable();
        }
     
    }//GEN-LAST:event_btnAmmoActionPerformed

    
    //set Values to reduce after shoot
    private void btnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS1ActionPerformed
          if(position==true){
                int val=Integer.parseInt(lblAmmo.getText());
                int newVal=val-1;
                lblAmmo.setText(Integer.toString(newVal));
        }else{
               btnAmmo.disable();
        
        }    
    }//GEN-LAST:event_btnS1ActionPerformed

    /**
     * @param sliderLevel
     */  boolean position=false;
   
    
        @Override
    public void update(int sliderLevel) {
       if(position==true){    
       if(sliderLevel>=20){
           btnS1.setText("Shoot on");
           btnS1.enable();
       }
       else if(sliderLevel<20){
            btnS1.setText("Shoot");
            btnS1.disable();
       }
       if(sliderLevel>=40){
           btnS2.setText("Sonar Operation on");
           btnS2.enable();
       }
       else if(sliderLevel<40){
           btnS2.setText("Sonar Operation");
           btnS2.disable();
       }
       if(sliderLevel>=60){
           btnS3.setText("Tomahwk Missile on");
           btnS3.enable();
       }
       else if(sliderLevel<60){
           btnS3.setText("Tomahawak Missile");
           btnS3.disable();
           
       } if(sliderLevel>=80){
           btnS4.setText("Trident-2 Missile on");
           btnS4.enable();
       }
       else if(sliderLevel<80){
           btnS4.setText("Trident -2 Missile");
            btnS4.disable();
       }
          }else{
              btnS1.setText("Shoot");
              btnS1.disable();
              btnS2.setText("Soner Operation");
               btnS2.disable();
              btnS3.setText("Tomahawk Missile");
               btnS3.disable();
              btnS4.setText("Trident -2 Missile");
               btnS4.disable();
              
          
          }
       
    }

    @Override
    public void updateText(String text) {
     txtSubmarineDisplay.setText("Main controller :"+text);
    }
    
    /**
     *
     * @param text
     */
    @Override
     public void setAreaClearedText(String text){
        lblAreaNotClearedSubmarine.setText(text);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmmo;
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnS2;
    private javax.swing.JButton btnS3;
    private javax.swing.JButton btnS4;
    private javax.swing.JButton btnSendSubmarine;
    private javax.swing.JButton btnSoldier;
    private javax.swing.JCheckBox checkBoxSubmarine;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAmmo;
    private javax.swing.JButton lblAreaNotClearedSubmarine;
    private javax.swing.JLabel lblSoldier;
    private javax.swing.JSpinner spinnerAmmo;
    private javax.swing.JSpinner spinnerSolder;
    private javax.swing.JTextField txtFieldSubmarine;
    private javax.swing.JTextPane txtSubmarineDisplay;
    // End of variables declaration//GEN-END:variables
}
