/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defence.system;

/**
 *
 * @author 94768
 */
public  class Submarine extends javax.swing.JFrame  implements DefenceObserver {
           private MainController mainController;
    /**
     * Creates new form Submarine
     * @param maincontroller
     */
    public Submarine( ) {
        initComponents();
         setVisible(true);
         setTitle("Submerine");
      
    }
    
        public void setMainController( MainController mainController){
        this.mainController=mainController;
    }
    
    public MainController getMainColler(){
            return mainController;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtSubmarineDisplay = new javax.swing.JTextPane();
        txtFieldSubmarine = new javax.swing.JTextField();
        btnSendSubmarine = new javax.swing.JButton();
        lblAreaNotClearedSubmarine = new javax.swing.JButton();
        checkBoxSubmarine = new javax.swing.JCheckBox();
        btnS1 = new javax.swing.JButton();
        btnS3 = new javax.swing.JButton();
        btnS2 = new javax.swing.JButton();
        btnS4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(txtSubmarineDisplay);

        txtFieldSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSubmarineActionPerformed(evt);
            }
        });

        btnSendSubmarine.setText("Send");
        btnSendSubmarine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSubmarineActionPerformed(evt);
            }
        });

        lblAreaNotClearedSubmarine.setText("Area Not Cleared");

        checkBoxSubmarine.setText("Position");
        checkBoxSubmarine.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxSubmarineItemStateChanged(evt);
            }
        });

        btnS1.setText("Shoot");

        btnS3.setText("Sonar Operation");

        btnS2.setText("Tomahawk Missile");

        btnS4.setText("Trident-2 Missile");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtFieldSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSendSubmarine)))
                    .addContainerGap(70, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnS2)
                        .addComponent(btnS1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnS3))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnS4)))
                    .addGap(28, 28, 28)
                    .addComponent(lblAreaNotClearedSubmarine)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAreaNotClearedSubmarine)
                    .addComponent(btnS1)
                    .addComponent(btnS3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnS2)
                    .addComponent(btnS4))
                .addGap(7, 7, 7)
                .addComponent(checkBoxSubmarine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendSubmarine))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSubmarineActionPerformed
          String textMessage=txtFieldSubmarine.getText();
         mainController.receivedMessage("Submarine : "+textMessage);
    }//GEN-LAST:event_btnSendSubmarineActionPerformed

    private void txtFieldSubmarineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSubmarineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSubmarineActionPerformed

    private void checkBoxSubmarineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxSubmarineItemStateChanged
        position = evt.getStateChange()==java.awt.event.ItemEvent.SELECTED; 
    }//GEN-LAST:event_checkBoxSubmarineItemStateChanged

    /**
     * @param sliderLevel
     */  boolean position=false;
   
    
        @Override
    public void update(int sliderLevel) {
       if(position==true){    
       if(sliderLevel>=20){
           btnS1.setText("Shoot on");
           btnS1.enable();
       }
       else if(sliderLevel<20){
            btnS1.setText("Shoot");
            btnS1.disable();
       }
       if(sliderLevel>=40){
           btnS2.setText("Sonar Operation on");
           btnS2.enable();
       }
       else if(sliderLevel<40){
           btnS2.setText("Sonar Operation");
           btnS2.disable();
       }
       if(sliderLevel>=60){
           btnS3.setText("Tomahwk Missile on");
           btnS3.enable();
       }
       else if(sliderLevel<60){
           btnS3.setText("Tomahawak Missile");
           btnS3.disable();
           
       } if(sliderLevel>=80){
           btnS4.setText("Trident-2 Missile on");
           btnS4.enable();
       }
       else if(sliderLevel<80){
           btnS4.setText("Trident -2 Missile");
            btnS4.disable();
       }
          }else{
              btnS1.setText("Shoot");
              btnS1.disable();
              btnS2.setText("Soner Operation");
               btnS2.disable();
              btnS3.setText("Tomahawk Missile");
               btnS3.disable();
              btnS4.setText("Trident -2 Missile");
               btnS4.disable();
              
          
          }
       
    }

    @Override
    public void updateText(String text) {
     txtSubmarineDisplay.setText("Main controller :"+text);
    }
    
    /**
     *
     * @param text
     */
    @Override
     public void setAreaClearedText(String text){
        lblAreaNotClearedSubmarine.setText(text);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnS2;
    private javax.swing.JButton btnS3;
    private javax.swing.JButton btnS4;
    private javax.swing.JButton btnSendSubmarine;
    private javax.swing.JCheckBox checkBoxSubmarine;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lblAreaNotClearedSubmarine;
    private javax.swing.JTextField txtFieldSubmarine;
    private javax.swing.JTextPane txtSubmarineDisplay;
    // End of variables declaration//GEN-END:variables
}
